# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20170823_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='reciever',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.User'),
        ),
        migrations.DeleteModel(
            name='Poke',
        ),
    ]
