# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_auto_20170825_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend_id',
            field=models.IntegerField(null=True),
        ),
    ]
