# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_friend_friend_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
