# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0009_friend_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend_id',
            new_name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='login_app.Friend'),
        ),
    ]
